theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: sita-vih.fr
  breadcrumb:
    position:  after-hero
  posts:
    default_image: false
    index:
      truncate_description: 200 # Set to 0 to disable truncate
      layout: grid
      options:
        hide_category: true